SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

insert into users(active,password,username,roles,name,lastname,mail) values (1,'admin','admin','ROLE_ADMIN,ROLE_STUDENT,ROLE_OFFERER','Admin','Admin','bancodetesina@gmail.com');
insert into users(active,password,username,roles,name,lastname,mail) values (1,'student','student','ROLE_STUDENT','Student','Student','bancodetesina@gmail.com');
insert into users(active,password,username,roles,name,lastname,mail) values (1,'offerer','offerer','ROLE_OFFERER','Offerer','Offerer','bancodetesina@gmail.com');
insert into users(active,password,username,roles,name,lastname,mail) values (1,'admin','adminonly','ROLE_ADMIN','AdminOnly','AdminOnly','bancodetesina@gmail.com');

insert into proyects(title,user_id,description,name,lastname,contact_mail,date_generation,overdue_proposal,deleted,last_date_actualization) values('Procesar y visualizar comentarios y calificaciones de usuarios',1,'Los usuarios de aplicaciones móviles generan a través de las app stores comentarios y calificaciones para describir su experiencia con las aplicaciones que descargan y usan. Estos comentarios, también llamados reviews, tienen información muy valiosa para retroalimentar el proceso de desarrollo de apps, por ejemplo, se pueden encontrar comentarios en forma de pedidos de nuevos features y reporte de errores. Este tipo de información es muy relevante para el desarrollo y la evolución de las aplicaciones móviles. Una tesina de licenciatura relacionada a este tema puede ser un software para procesar y visualizar estos comentarios y calificaciones de los usuarios. Existe bibliografía e implementaciones que se pueden usar como base para esta tarea  Literatura orientativa https://ieeexplore.ieee.org/document/8920629' ,'Andres','Rojas Paredes','bancodetesina@gmail.com','2022-05-12',0,0,'2022-07-28');
insert into proyects(title,user_id,description,name,lastname,contact_mail,date_generation,overdue_proposal,deleted,last_date_actualization) values('Modelo de detección temprana de deserción en la universidad',1,'Los científicos de datos(Data Mininig) descubrimos variables o patrones que explican problemas, como la deserción universitaria. La idea es armar un modelo predictivo (que detecte la deserción antes que ocurra), basado en las variables de Moodle/ Guarani de cada alumno. Material de Orientación: https://www.youtube.com/watch?v=ea_wXTBM9KE','Offerer','Offerer','bancodetesina@gmail.com','2022-05-12',0,0,'2022-07-28');
insert into proyects(title,user_id,description,name,lastname,contact_mail,date_generation,overdue_proposal,deleted,last_date_actualization) values('Visualización de demanda',1,'El problema de asignación de aulas selecciona un aula para cada materia de una lista, tomando en cuenta horarios, capacidades y solapamientos. Se cuenta con una aplicación que realiza la asignación de aulas, sin considerar las características de la demanda. Se desea extender la herramienta existente, de modo que se genere una representación visual de la demanda; en particular, dada una lista de materias y horarios se desea obtener el grafo de conflictos (cada materia es un vértice y dos materias están relacionadas si su dictado se solapa en el tiempo), grafo que debe ser procesado para que su visualización resulte fácil de comprender...','Offerer','Offerer','bancodetesina@gmail.com','2022-05-12',0,0,'2022-07-28');
insert into proyects(title,user_id,description,name,lastname,contact_mail,date_generation,overdue_proposal,deleted,last_date_actualization) values('Desarrollo de Plataforma de Banco de Proyecto de la Tesina de Licenciatura.',1,'Desarrollar una plataforma que permita a los profesores de la UNGS plantear proyectos para ser llevados adelante en el marco del Taller de Tesina de la Licenciatura en Sistemas.','Iván','Jourdan','bancodetesina@gmail.com','2022-05-12',0,0,'2022-07-28');
insert into proyects(title,user_id,description,name,lastname,contact_mail,date_generation,overdue_proposal,deleted,last_date_actualization) values('Interfaz gráfica interactiva',1,'El problema de asignación de aulas selecciona un aula para cada materia de una lista, tomando en cuenta horarios, capacidades y solapamientos. Se cuenta con una aplicación por consola que realiza la asignación de aulas, un proceso que demora varios minutos. Se desea implementar una interfaz gráfica que admita el reporte de errores y muestre amigablemente el avance del proceso, con la posibilidad de indicar en cualquier momento que se desea detener la ejecución.','Javier','Martínez-Viademonte','bancodetesina@gmail.com','2022-05-12',0,0,'2022-07-28');
insert into proyects(title,user_id,description,name,lastname,contact_mail,date_generation,overdue_proposal,deleted,last_date_actualization) values('Extracción de señal digital de Electrocardiogramas',1,'Por ser práctico, y económicos, los electrocardiógrafos devuelven los registros, o electrocardiogramas (ECG), impresos en un papel con un grilla, la cuál permite al profesional de la salud estudiar cada medición. El registro digital de estos electrocardiogramas es una foto, generada con teléfono celular. En particular, este formato imposibilita el estudio de las señales mediante procesamiento digital que asista a los profesionales de la salud en el diagnóstico','Iván','Jourdan','bancodetesina@gmail.com','2022-05-12',0,0,'2022-07-28');

insert into tags(tagname) values('Machine Learning');
insert into tags(tagname) values('SQL');
insert into tags(tagname) values('Application');
insert into tags(tagname) values('Virtualization');

insert into config(view_time_proposal,delete_time_proposal,max_amoung_applicants) values(1095,1825,3);